---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files

      - id: mixed-line-ending
        alias: check-line-endings
        name: check-line-endings
        args: ['--fix=no']

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint

  - repo: https://github.com/jmknoble/json-indent
    rev: v2.6.5
    hooks:
      - id: json-indent
        args: ['--newlines=linux']

  - repo: https://github.com/jmknoble/markdown-toc
    rev: v0.3.0
    hooks:
      - id: markdown-toc
        args: ['--heading-level', '2', '--skip-level', '1']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version
    rev: v0.7.0
    hooks:
      # Emulate isort
      - id: ruff
        name: ruff-isort
        alias: ruff-isort
        args: ['--config', 'lint.select = ["I"]', '--fix']

      # Auto-format Python code
      - id: ruff-format
        # args: ['project-dir/']

      # Run the linter
      - id: ruff
        # args: ['project-dir/']
