---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3

repos:
  - repo: https://github.com/jmknoble/json-indent
    rev: v2.2.2
    hooks:
      - id: json-indent
...
